{"name": "Получение заказов конкретного пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 401\n +  where 404 = <Response [404]>.status_code", "trace": "tests\\test_get_user_orders.py:21: in test_get_orders_without_authorization\n    assert response.status_code == 401\nE   assert 404 == 401\nE    +  where 404 = <Response [404]>.status_code\n        response   = <Response [404]>\n        self       = <tests.test_get_user_orders.TestGetUserOrders object at 0x0000020615AC07D0>"}, "description": "Неавторизованный пользователь, проверка кода и текста ответа", "start": 1719837917820, "stop": 1719837918134, "uuid": "42201ace-c9fd-47d2-9bae-e2b75914275d", "historyId": "b480c74548b44aed6506e24e9da7cc5b", "testCaseId": "b480c74548b44aed6506e24e9da7cc5b", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_orders_without_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "DESKTOP-8VJF26I"}, {"name": "thread", "value": "22712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}